name: "jenny build" 

on: [push]

jobs:
  build_job:
    runs-on: ubuntu-latest
    name:  Build with Jenny
    steps:
    - uses: actions/checkout@v2
    - uses: hmngwy/jenny@master
    - uses: JamesIves/github-pages-deploy-action@v4.6.4
      with:
        branch: gh-pages
        folder: .dist
